// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfDBGuCGYgxB7a2cLHt9nTZ466EkrYii0',
    appId: '1:434308019325:web:b0b45d75237ab1c6fb2d14',
    messagingSenderId: '434308019325',
    projectId: 'skyoption-sky-trade',
    authDomain: 'skyoption-sky-trade.firebaseapp.com',
    storageBucket: 'skyoption-sky-trade.appspot.com',
    measurementId: 'G-Y2X0NTPF26',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCw2wVnP7u-Q-eW4bsK4yW2Ipbjq4GQras',
    appId: '1:434308019325:android:15544976e55c01e2fb2d14',
    messagingSenderId: '434308019325',
    projectId: 'skyoption-sky-trade',
    storageBucket: 'skyoption-sky-trade.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDClcD7n9axuTk2ux0omDed8dhNGMK6Y9A',
    appId: '1:434308019325:ios:b12f3df7e1a98f38fb2d14',
    messagingSenderId: '434308019325',
    projectId: 'skyoption-sky-trade',
    storageBucket: 'skyoption-sky-trade.appspot.com',
    iosBundleId: 'com.skyoption.skytrade',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDClcD7n9axuTk2ux0omDed8dhNGMK6Y9A',
    appId: '1:434308019325:ios:691326bca2e3a2fcfb2d14',
    messagingSenderId: '434308019325',
    projectId: 'skyoption-sky-trade',
    storageBucket: 'skyoption-sky-trade.appspot.com',
    iosBundleId: 'com.sky.trading.RunnerTests',
  );
}
