// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'features/main/models/schema/connected_account_info_model.dart';
import 'features/platform_settings/models/schema/app_log_model.dart';
import 'features/symbols/models/schema/symbol_model.dart';
import 'features/trade/models/schema/order_model.dart';
import 'features/trade/models/schema/position_model.dart';
import 'features/trade_history/models/schema/account_founds_model.dart';
import 'features/trade_history/models/schema/history_actions_model.dart';
import 'features/trade_history/models/schema/history_pending_model.dart';
import 'features/trade_history/models/schema/history_position_model.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 2384419387885785736),
    name: 'AccountFoundsModel',
    lastPropertyId: const obx_int.IdUid(9, 1187143740735390664),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 7736967787259594236),
        name: 'id',
        type: 6,
        flags: 129,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 3025822608514203894),
        name: 'type',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 2434473873990029782),
        name: 'amount',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 8394686117273403112),
        name: 'comment',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 700632556237838616),
        name: 'source',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 9215011083725252566),
        name: 'date',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 603683612939231040),
        name: 'commission',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 4835548040332840071),
        name: 'isA',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 1187143740735390664),
        name: 'swap',
        type: 8,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 292294618408102954),
    name: 'AppLogModel',
    lastPropertyId: const obx_int.IdUid(4, 2447121136076303867),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 21926395154318994),
        name: 'id',
        type: 6,
        flags: 129,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 1197298506486507181),
        name: 'accountNumber',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 6791428538117647495),
        name: 'event',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 2447121136076303867),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(3, 6819238407960141896),
    name: 'ConnectedAccountInfoModel',
    lastPropertyId: const obx_int.IdUid(18, 6783412318483006806),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 7624372514076485234),
        name: 'id',
        type: 6,
        flags: 129,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 782715367525978092),
        name: 'group',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 9024907790895150127),
        name: 'fullName',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 5688888940874967866),
        name: 'leverage',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 8762595280426104864),
        name: 'balance',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 6301156627829290936),
        name: 'credit',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 2940428762740808410),
        name: 'equity',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 2768722181023175179),
        name: 'floating',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 7552694142075383597),
        name: 'margin',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 9136071368696484355),
        name: 'marginFree',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 7076433187523878503),
        name: 'marginLevel',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 614618755262330937),
        name: 'isSwapFree',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 6001718455669590038),
        name: 'limitPositions',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(14, 7547266810733707817),
        name: 'limitPending',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(15, 2360696699661662833),
        name: 'rights',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(16, 8420812045340164149),
        name: 'isDefault',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(17, 2239272884445062276),
        name: 'marginCallLevel',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(18, 6783412318483006806),
        name: 'connectionMode',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(4, 2536116966149953155),
    name: 'HistoryActionModel',
    lastPropertyId: const obx_int.IdUid(12, 2107107144976646402),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 1308243087087502044),
        name: 'id',
        type: 6,
        flags: 129,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 2179703332374869399),
        name: 'account',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 8564466990332157064),
        name: 'symbol',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 5817122663099151755),
        name: 'source',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 1555222458269702331),
        name: 'direction',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 8115693284873553859),
        name: 'type',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 1813794867312907471),
        name: 'volume',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 2061433318188141305),
        name: 'commission',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 255556997758175894),
        name: 'price',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 2809809226722612110),
        name: 'profit',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 6699319213948317292),
        name: 'createdAt',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 2107107144976646402),
        name: 'tradeId',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(5, 1519417629578442686),
    name: 'HistoryPendingModel',
    lastPropertyId: const obx_int.IdUid(14, 8766400126738177687),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 6369396416203597406),
        name: 'id',
        type: 6,
        flags: 129,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 6881092450433173691),
        name: 'symbol',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 9203379904806857777),
        name: 'direction',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 6791612768038517833),
        name: 'expirationDate',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 3626966480297298856),
        name: 'createdAt',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 9195496314449510243),
        name: 'volume',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 1161225712903992189),
        name: 'openPrice',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 8337688080513766366),
        name: 'tp',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 8210832378699969666),
        name: 'sl',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 5405799926405285855),
        name: 'type',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 7119267963216704079),
        name: 'comment',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 6751373730887845517),
        name: 'openTime',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 1198249425338795441),
        name: 'closedAt',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(14, 8766400126738177687),
        name: 'reason',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(6, 528727368255404921),
    name: 'HistoryPositionModel',
    lastPropertyId: const obx_int.IdUid(16, 1930980584724033328),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 7214608133529957691),
        name: 'id',
        type: 6,
        flags: 129,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 7643175907198260294),
        name: 'symbol',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 8302521392077289111),
        name: 'direction',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 1162224930429938402),
        name: 'volumeInit',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 6150523087507770050),
        name: 'volumeCurrent',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 1201294650681068808),
        name: 'openPrice',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 4267053265207559270),
        name: 'tp',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 4820575548146828313),
        name: 'sl',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 3862510055468765882),
        name: 'floating',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 5930029976137209527),
        name: 'margin',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 9001406209291027542),
        name: 'commission',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 6201536893175074563),
        name: 'swap',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 3787154059783703131),
        name: 'comment',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(14, 303597806301161682),
        name: 'openTime',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(15, 8960836280154486947),
        name: 'closePrice',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(16, 1930980584724033328),
        name: 'closeTime',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(7, 6972186170766863323),
    name: 'OrderModel',
    lastPropertyId: const obx_int.IdUid(11, 6195472857991703214),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 3545564244629558025),
        name: 'id',
        type: 6,
        flags: 129,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 8779745412008758889),
        name: 'symbol',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 708214739869344398),
        name: 'direction',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 1325266521433787791),
        name: 'expirationDate',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 4046108729505097803),
        name: 'createdAt',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 6991764678512468426),
        name: 'volume',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 7704139499984626390),
        name: 'openPrice',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 4125077062794842847),
        name: 'tp',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 4222004725621330539),
        name: 'sl',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 8172943118293460863),
        name: 'comment',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 6195472857991703214),
        name: 'openTime',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(8, 6407964669392246230),
    name: 'PositionModel',
    lastPropertyId: const obx_int.IdUid(14, 6189243791416056312),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 8582995034856801865),
        name: 'id',
        type: 6,
        flags: 129,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 7038447580090804911),
        name: 'groupSymbol',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 6114543853265333354),
        name: 'direction',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 675879817132707494),
        name: 'volumeInit',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 975022385411459356),
        name: 'volumeCurrent',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 2500387866091065277),
        name: 'openPrice',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 8867354277418992800),
        name: 'tp',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 2816399433181308577),
        name: 'sl',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 4947361875171357747),
        name: 'floating',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 4255376439947046593),
        name: 'margin',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 7710839867053207817),
        name: 'commission',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 4884789823867012206),
        name: 'swap',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 873687808097883609),
        name: 'comment',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(14, 6189243791416056312),
        name: 'openTime',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(9, 8739303672984238494),
    name: 'SymbolModel',
    lastPropertyId: const obx_int.IdUid(29, 96949791538438046),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 3386970308014346498),
        name: 'id',
        type: 6,
        flags: 129,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 2043335689912472465),
        name: 'sector',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 8501316492858498876),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 390234520147314514),
        name: 'leverage',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 311507672304309112),
        name: 'ask',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 3423562954368156896),
        name: 'bid',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 9164212459303633938),
        name: 'marginCurrency',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 7142619388070025246),
        name: 'description',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 2150692454924333530),
        name: 'profitCurrency',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 2519548324626421018),
        name: 'timestamp',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 2568045741930259543),
        name: 'groupSymbol',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 1644291605565424125),
        name: 'contractSize',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 5554238086074336941),
        name: 'tickSize',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(14, 90887441542514395),
        name: 'profitRatio',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(15, 2978681615747434452),
        name: 'marginRatio',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(16, 9169493404012905910),
        name: 'swapLong',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(17, 434952594951169374),
        name: 'swapShort',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(18, 501010083300837508),
        name: 'commissionIn',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(19, 7240063451980361146),
        name: 'commissionOut',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(20, 2592552030308298371),
        name: 'volumeMin',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(21, 2755636113525235239),
        name: 'volumeMax',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(22, 7017090924776818513),
        name: 'volumeStep',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(23, 3324961345799008995),
        name: 'askDifference',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(24, 1803687216228942760),
        name: 'bidDifference',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(25, 4651297936626483924),
        name: 'stopLevel',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(26, 2991775263073024796),
        name: 'isFav',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(27, 5015185211794096477),
        name: 'index',
        type: 6,
        flags: 8,
        indexId: const obx_int.IdUid(1, 832188631631265750),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(28, 7362878173354782119),
        name: 'askColorHex',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(29, 96949791538438046),
        name: 'bidColorHex',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    entities: _entities,
    lastEntityId: const obx_int.IdUid(9, 8739303672984238494),
    lastIndexId: const obx_int.IdUid(1, 832188631631265750),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    AccountFoundsModel: obx_int.EntityDefinition<AccountFoundsModel>(
      model: _entities[0],
      toOneRelations: (AccountFoundsModel object) => [],
      toManyRelations: (AccountFoundsModel object) => {},
      getId: (AccountFoundsModel object) => object.id,
      setId: (AccountFoundsModel object, int id) {
        object.id = id;
      },
      objectToFB: (AccountFoundsModel object, fb.Builder fbb) {
        final typeOffset = fbb.writeString(object.type);
        final commentOffset = fbb.writeString(object.comment);
        final sourceOffset = fbb.writeString(object.source);
        final dateOffset = fbb.writeString(object.date);
        final isAOffset = fbb.writeString(object.isA);
        fbb.startTable(10);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, typeOffset);
        fbb.addFloat64(2, object.amount);
        fbb.addOffset(3, commentOffset);
        fbb.addOffset(4, sourceOffset);
        fbb.addOffset(5, dateOffset);
        fbb.addFloat64(6, object.commission);
        fbb.addOffset(7, isAOffset);
        fbb.addFloat64(8, object.swap);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final amountParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        final typeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final commentParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final sourceParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final dateParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 14, '');
        final object =
            AccountFoundsModel(
                id: idParam,
                amount: amountParam,
                type: typeParam,
                comment: commentParam,
                source: sourceParam,
                date: dateParam,
              )
              ..commission = const fb.Float64Reader().vTableGet(
                buffer,
                rootOffset,
                16,
                0,
              )
              ..isA = const fb.StringReader(
                asciiOptimization: true,
              ).vTableGet(buffer, rootOffset, 18, '')
              ..swap = const fb.Float64Reader().vTableGet(
                buffer,
                rootOffset,
                20,
                0,
              );

        return object;
      },
    ),
    AppLogModel: obx_int.EntityDefinition<AppLogModel>(
      model: _entities[1],
      toOneRelations: (AppLogModel object) => [],
      toManyRelations: (AppLogModel object) => {},
      getId: (AppLogModel object) => object.id,
      setId: (AppLogModel object, int id) {
        object.id = id;
      },
      objectToFB: (AppLogModel object, fb.Builder fbb) {
        final eventOffset = fbb.writeString(object.event);
        fbb.startTable(5);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.accountNumber);
        fbb.addOffset(2, eventOffset);
        fbb.addInt64(3, object.createdAt.millisecondsSinceEpoch);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final eventParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0),
        );
        final accountNumberParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        final object = AppLogModel(
          id: idParam,
          event: eventParam,
          createdAt: createdAtParam,
          accountNumber: accountNumberParam,
        );

        return object;
      },
    ),
    ConnectedAccountInfoModel:
        obx_int.EntityDefinition<ConnectedAccountInfoModel>(
          model: _entities[2],
          toOneRelations: (ConnectedAccountInfoModel object) => [],
          toManyRelations: (ConnectedAccountInfoModel object) => {},
          getId: (ConnectedAccountInfoModel object) => object.id,
          setId: (ConnectedAccountInfoModel object, int id) {
            object.id = id;
          },
          objectToFB: (ConnectedAccountInfoModel object, fb.Builder fbb) {
            final groupOffset = fbb.writeString(object.group);
            final fullNameOffset = fbb.writeString(object.fullName);
            final connectionModeOffset = fbb.writeString(object.connectionMode);
            fbb.startTable(19);
            fbb.addInt64(0, object.id);
            fbb.addOffset(1, groupOffset);
            fbb.addOffset(2, fullNameOffset);
            fbb.addInt64(3, object.leverage);
            fbb.addFloat64(4, object.balance);
            fbb.addFloat64(5, object.credit);
            fbb.addFloat64(6, object.equity);
            fbb.addFloat64(7, object.floating);
            fbb.addFloat64(8, object.margin);
            fbb.addFloat64(9, object.marginFree);
            fbb.addFloat64(10, object.marginLevel);
            fbb.addBool(11, object.isSwapFree);
            fbb.addInt64(12, object.limitPositions);
            fbb.addInt64(13, object.limitPending);
            fbb.addInt64(14, object.rights);
            fbb.addBool(15, object.isDefault);
            fbb.addFloat64(16, object.marginCallLevel);
            fbb.addOffset(17, connectionModeOffset);
            fbb.finish(fbb.endTable());
            return object.id;
          },
          objectFromFB: (obx.Store store, ByteData fbData) {
            final buffer = fb.BufferContext(fbData);
            final rootOffset = buffer.derefObject(0);
            final idParam = const fb.Int64Reader().vTableGet(
              buffer,
              rootOffset,
              4,
              0,
            );
            final groupParam = const fb.StringReader(
              asciiOptimization: true,
            ).vTableGet(buffer, rootOffset, 6, '');
            final leverageParam = const fb.Int64Reader().vTableGet(
              buffer,
              rootOffset,
              10,
              0,
            );
            final balanceParam = const fb.Float64Reader().vTableGet(
              buffer,
              rootOffset,
              12,
              0,
            );
            final creditParam = const fb.Float64Reader().vTableGet(
              buffer,
              rootOffset,
              14,
              0,
            );
            final equityParam = const fb.Float64Reader().vTableGet(
              buffer,
              rootOffset,
              16,
              0,
            );
            final floatingParam = const fb.Float64Reader().vTableGet(
              buffer,
              rootOffset,
              18,
              0,
            );
            final marginParam = const fb.Float64Reader().vTableGet(
              buffer,
              rootOffset,
              20,
              0,
            );
            final marginFreeParam = const fb.Float64Reader().vTableGet(
              buffer,
              rootOffset,
              22,
              0,
            );
            final marginLevelParam = const fb.Float64Reader().vTableGetNullable(
              buffer,
              rootOffset,
              24,
            );
            final isSwapFreeParam = const fb.BoolReader().vTableGetNullable(
              buffer,
              rootOffset,
              26,
            );
            final fullNameParam = const fb.StringReader(
              asciiOptimization: true,
            ).vTableGet(buffer, rootOffset, 8, '');
            final limitPositionsParam = const fb.Int64Reader()
                .vTableGetNullable(buffer, rootOffset, 28);
            final limitPendingParam = const fb.Int64Reader().vTableGetNullable(
              buffer,
              rootOffset,
              30,
            );
            final rightsParam = const fb.Int64Reader().vTableGetNullable(
              buffer,
              rootOffset,
              32,
            );
            final isDefaultParam = const fb.BoolReader().vTableGet(
              buffer,
              rootOffset,
              34,
              false,
            );
            final marginCallLevelParam = const fb.Float64Reader().vTableGet(
              buffer,
              rootOffset,
              36,
              0,
            );
            final connectionModeParam = const fb.StringReader(
              asciiOptimization: true,
            ).vTableGet(buffer, rootOffset, 38, '');
            final object = ConnectedAccountInfoModel(
              id: idParam,
              group: groupParam,
              leverage: leverageParam,
              balance: balanceParam,
              credit: creditParam,
              equity: equityParam,
              floating: floatingParam,
              margin: marginParam,
              marginFree: marginFreeParam,
              marginLevel: marginLevelParam,
              isSwapFree: isSwapFreeParam,
              fullName: fullNameParam,
              limitPositions: limitPositionsParam,
              limitPending: limitPendingParam,
              rights: rightsParam,
              isDefault: isDefaultParam,
              marginCallLevel: marginCallLevelParam,
              connectionMode: connectionModeParam,
            );

            return object;
          },
        ),
    HistoryActionModel: obx_int.EntityDefinition<HistoryActionModel>(
      model: _entities[3],
      toOneRelations: (HistoryActionModel object) => [],
      toManyRelations: (HistoryActionModel object) => {},
      getId: (HistoryActionModel object) => object.id,
      setId: (HistoryActionModel object, int id) {
        object.id = id;
      },
      objectToFB: (HistoryActionModel object, fb.Builder fbb) {
        final symbolOffset = fbb.writeString(object.symbol);
        final sourceOffset = fbb.writeString(object.source);
        final directionOffset = fbb.writeString(object.direction);
        final typeOffset = fbb.writeString(object.type);
        final createdAtOffset = fbb.writeString(object.createdAt);
        fbb.startTable(13);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.account);
        fbb.addOffset(2, symbolOffset);
        fbb.addOffset(3, sourceOffset);
        fbb.addOffset(4, directionOffset);
        fbb.addOffset(5, typeOffset);
        fbb.addFloat64(6, object.volume);
        fbb.addFloat64(7, object.commission);
        fbb.addFloat64(8, object.price);
        fbb.addFloat64(9, object.profit);
        fbb.addOffset(10, createdAtOffset);
        fbb.addInt64(11, object.tradeId);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final createdAtParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 24, '');
        final profitParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          22,
          0,
        );
        final priceParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          20,
          0,
        );
        final directionParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final volumeParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          16,
          0,
        );
        final typeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 14, '');
        final sourceParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final symbolParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final commissionParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          18,
          0,
        );
        final accountParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        final tradeIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          26,
          0,
        );
        final object = HistoryActionModel(
          id: idParam,
          createdAt: createdAtParam,
          profit: profitParam,
          price: priceParam,
          direction: directionParam,
          volume: volumeParam,
          type: typeParam,
          source: sourceParam,
          symbol: symbolParam,
          commission: commissionParam,
          account: accountParam,
          tradeId: tradeIdParam,
        );

        return object;
      },
    ),
    HistoryPendingModel: obx_int.EntityDefinition<HistoryPendingModel>(
      model: _entities[4],
      toOneRelations: (HistoryPendingModel object) => [],
      toManyRelations: (HistoryPendingModel object) => {},
      getId: (HistoryPendingModel object) => object.id,
      setId: (HistoryPendingModel object, int id) {
        object.id = id;
      },
      objectToFB: (HistoryPendingModel object, fb.Builder fbb) {
        final symbolOffset = fbb.writeString(object.symbol);
        final directionOffset = fbb.writeString(object.direction);
        final expirationDateOffset = fbb.writeString(object.expirationDate);
        final createdAtOffset = fbb.writeString(object.createdAt);
        final commentOffset = fbb.writeString(object.comment);
        final openTimeOffset = fbb.writeString(object.openTime);
        final closedAtOffset = fbb.writeString(object.closedAt);
        final reasonOffset = fbb.writeString(object.reason);
        fbb.startTable(15);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, symbolOffset);
        fbb.addOffset(2, directionOffset);
        fbb.addOffset(3, expirationDateOffset);
        fbb.addOffset(4, createdAtOffset);
        fbb.addFloat64(5, object.volume);
        fbb.addFloat64(6, object.openPrice);
        fbb.addFloat64(7, object.tp);
        fbb.addFloat64(8, object.sl);
        fbb.addInt64(9, object.type);
        fbb.addOffset(10, commentOffset);
        fbb.addOffset(11, openTimeOffset);
        fbb.addOffset(12, closedAtOffset);
        fbb.addOffset(13, reasonOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final expirationDateParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final symbolParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final directionParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final closedAtParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 28, '');
        final reasonParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 30, '');
        final volumeParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          14,
          0,
        );
        final tpParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          18,
          0,
        );
        final slParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          20,
          0,
        );
        final openPriceParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          16,
          0,
        );
        final typeParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          22,
          0,
        );
        final createdAtParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final commentParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 24, '');
        final openTimeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 26, '');
        final object = HistoryPendingModel(
          id: idParam,
          expirationDate: expirationDateParam,
          symbol: symbolParam,
          direction: directionParam,
          closedAt: closedAtParam,
          reason: reasonParam,
          volume: volumeParam,
          tp: tpParam,
          sl: slParam,
          openPrice: openPriceParam,
          type: typeParam,
          createdAt: createdAtParam,
          comment: commentParam,
          openTime: openTimeParam,
        );

        return object;
      },
    ),
    HistoryPositionModel: obx_int.EntityDefinition<HistoryPositionModel>(
      model: _entities[5],
      toOneRelations: (HistoryPositionModel object) => [],
      toManyRelations: (HistoryPositionModel object) => {},
      getId: (HistoryPositionModel object) => object.id,
      setId: (HistoryPositionModel object, int id) {
        object.id = id;
      },
      objectToFB: (HistoryPositionModel object, fb.Builder fbb) {
        final symbolOffset = fbb.writeString(object.symbol);
        final directionOffset = fbb.writeString(object.direction);
        final commentOffset = fbb.writeString(object.comment);
        final openTimeOffset = fbb.writeString(object.openTime);
        final closeTimeOffset = fbb.writeString(object.closeTime);
        fbb.startTable(17);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, symbolOffset);
        fbb.addOffset(2, directionOffset);
        fbb.addFloat64(3, object.volumeInit);
        fbb.addFloat64(4, object.volumeCurrent);
        fbb.addFloat64(5, object.openPrice);
        fbb.addFloat64(6, object.tp);
        fbb.addFloat64(7, object.sl);
        fbb.addFloat64(8, object.floating);
        fbb.addFloat64(9, object.margin);
        fbb.addFloat64(10, object.commission);
        fbb.addFloat64(11, object.swap);
        fbb.addOffset(12, commentOffset);
        fbb.addOffset(13, openTimeOffset);
        fbb.addFloat64(14, object.closePrice);
        fbb.addOffset(15, closeTimeOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final symbolParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final directionParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final volumeInitParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final closeTimeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 34, '');
        final volumeCurrentParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        final openPriceParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          14,
          0,
        );
        final tpParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          16,
          0,
        );
        final slParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          18,
          0,
        );
        final closePriceParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          32,
          0,
        );
        final floatingParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          20,
          0,
        );
        final marginParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          22,
          0,
        );
        final commissionParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          24,
          0,
        );
        final swapParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          26,
          0,
        );
        final commentParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 28, '');
        final openTimeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 30, '');
        final object = HistoryPositionModel(
          id: idParam,
          symbol: symbolParam,
          direction: directionParam,
          volumeInit: volumeInitParam,
          closeTime: closeTimeParam,
          volumeCurrent: volumeCurrentParam,
          openPrice: openPriceParam,
          tp: tpParam,
          sl: slParam,
          closePrice: closePriceParam,
          floating: floatingParam,
          margin: marginParam,
          commission: commissionParam,
          swap: swapParam,
          comment: commentParam,
          openTime: openTimeParam,
        );

        return object;
      },
    ),
    OrderModel: obx_int.EntityDefinition<OrderModel>(
      model: _entities[6],
      toOneRelations: (OrderModel object) => [],
      toManyRelations: (OrderModel object) => {},
      getId: (OrderModel object) => object.id,
      setId: (OrderModel object, int id) {
        object.id = id;
      },
      objectToFB: (OrderModel object, fb.Builder fbb) {
        final symbolOffset = fbb.writeString(object.symbol);
        final directionOffset = fbb.writeString(object.direction);
        final expirationDateOffset = fbb.writeString(object.expirationDate);
        final createdAtOffset = fbb.writeString(object.createdAt);
        final commentOffset = fbb.writeString(object.comment);
        final openTimeOffset = fbb.writeString(object.openTime);
        fbb.startTable(12);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, symbolOffset);
        fbb.addOffset(2, directionOffset);
        fbb.addOffset(3, expirationDateOffset);
        fbb.addOffset(4, createdAtOffset);
        fbb.addFloat64(5, object.volume);
        fbb.addFloat64(6, object.openPrice);
        fbb.addFloat64(7, object.tp);
        fbb.addFloat64(8, object.sl);
        fbb.addOffset(9, commentOffset);
        fbb.addOffset(10, openTimeOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final expirationDateParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final symbolParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final directionParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final volumeParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          14,
          0,
        );
        final tpParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          18,
          0,
        );
        final slParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          20,
          0,
        );
        final openPriceParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          16,
          0,
        );
        final createdAtParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final commentParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 22, '');
        final openTimeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 24, '');
        final object = OrderModel(
          id: idParam,
          expirationDate: expirationDateParam,
          symbol: symbolParam,
          direction: directionParam,
          volume: volumeParam,
          tp: tpParam,
          sl: slParam,
          openPrice: openPriceParam,
          createdAt: createdAtParam,
          comment: commentParam,
          openTime: openTimeParam,
        );

        return object;
      },
    ),
    PositionModel: obx_int.EntityDefinition<PositionModel>(
      model: _entities[7],
      toOneRelations: (PositionModel object) => [],
      toManyRelations: (PositionModel object) => {},
      getId: (PositionModel object) => object.id,
      setId: (PositionModel object, int id) {
        object.id = id;
      },
      objectToFB: (PositionModel object, fb.Builder fbb) {
        final groupSymbolOffset = fbb.writeString(object.groupSymbol);
        final directionOffset = fbb.writeString(object.direction);
        final commentOffset = fbb.writeString(object.comment);
        final openTimeOffset = fbb.writeString(object.openTime);
        fbb.startTable(15);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, groupSymbolOffset);
        fbb.addOffset(2, directionOffset);
        fbb.addFloat64(3, object.volumeInit);
        fbb.addFloat64(4, object.volumeCurrent);
        fbb.addFloat64(5, object.openPrice);
        fbb.addFloat64(6, object.tp);
        fbb.addFloat64(7, object.sl);
        fbb.addFloat64(8, object.floating);
        fbb.addFloat64(9, object.margin);
        fbb.addFloat64(10, object.commission);
        fbb.addFloat64(11, object.swap);
        fbb.addOffset(12, commentOffset);
        fbb.addOffset(13, openTimeOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final groupSymbolParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final directionParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final volumeInitParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final volumeCurrentParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        final openPriceParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          14,
          0,
        );
        final tpParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          16,
          0,
        );
        final slParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          18,
          0,
        );
        final floatingParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          20,
          0,
        );
        final marginParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          22,
          0,
        );
        final commissionParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          24,
          0,
        );
        final swapParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          26,
          0,
        );
        final commentParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 28, '');
        final openTimeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 30, '');
        final object = PositionModel(
          id: idParam,
          groupSymbol: groupSymbolParam,
          direction: directionParam,
          volumeInit: volumeInitParam,
          volumeCurrent: volumeCurrentParam,
          openPrice: openPriceParam,
          tp: tpParam,
          sl: slParam,
          floating: floatingParam,
          margin: marginParam,
          commission: commissionParam,
          swap: swapParam,
          comment: commentParam,
          openTime: openTimeParam,
        );

        return object;
      },
    ),
    SymbolModel: obx_int.EntityDefinition<SymbolModel>(
      model: _entities[8],
      toOneRelations: (SymbolModel object) => [],
      toManyRelations: (SymbolModel object) => {},
      getId: (SymbolModel object) => object.id,
      setId: (SymbolModel object, int id) {
        object.id = id;
      },
      objectToFB: (SymbolModel object, fb.Builder fbb) {
        final sectorOffset = fbb.writeString(object.sector);
        final nameOffset = fbb.writeString(object.name);
        final marginCurrencyOffset = fbb.writeString(object.marginCurrency);
        final descriptionOffset = fbb.writeString(object.description);
        final profitCurrencyOffset = fbb.writeString(object.profitCurrency);
        final askColorHexOffset = fbb.writeString(object.askColorHex);
        final bidColorHexOffset = fbb.writeString(object.bidColorHex);
        fbb.startTable(30);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, sectorOffset);
        fbb.addOffset(2, nameOffset);
        fbb.addInt64(3, object.leverage);
        fbb.addFloat64(4, object.ask);
        fbb.addFloat64(5, object.bid);
        fbb.addOffset(6, marginCurrencyOffset);
        fbb.addOffset(7, descriptionOffset);
        fbb.addOffset(8, profitCurrencyOffset);
        fbb.addInt64(9, object.timestamp);
        fbb.addFloat64(10, object.groupSymbol);
        fbb.addFloat64(11, object.contractSize);
        fbb.addFloat64(12, object.tickSize);
        fbb.addFloat64(13, object.profitRatio);
        fbb.addFloat64(14, object.marginRatio);
        fbb.addFloat64(15, object.swapLong);
        fbb.addFloat64(16, object.swapShort);
        fbb.addFloat64(17, object.commissionIn);
        fbb.addFloat64(18, object.commissionOut);
        fbb.addFloat64(19, object.volumeMin);
        fbb.addFloat64(20, object.volumeMax);
        fbb.addFloat64(21, object.volumeStep);
        fbb.addFloat64(22, object.askDifference);
        fbb.addFloat64(23, object.bidDifference);
        fbb.addInt64(24, object.stopLevel);
        fbb.addBool(25, object.isFav);
        fbb.addInt64(26, object.index);
        fbb.addOffset(27, askColorHexOffset);
        fbb.addOffset(28, bidColorHexOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final marginCurrencyParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 16, '');
        final profitCurrencyParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 20, '');
        final descriptionParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 18, '');
        final sectorParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final leverageParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final askParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        final bidParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          14,
          0,
        );
        final askColorHexParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 58, '');
        final bidColorHexParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 60, '');
        final timestampParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          22,
          0,
        );
        final groupSymbolParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          24,
          0,
        );
        final contractSizeParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          26,
          0,
        );
        final tickSizeParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          28,
          0,
        );
        final profitRatioParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          30,
          0,
        );
        final marginRatioParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          32,
          0,
        );
        final swapLongParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          34,
          0,
        );
        final swapShortParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          36,
          0,
        );
        final commissionInParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          38,
          0,
        );
        final commissionOutParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          40,
          0,
        );
        final volumeMinParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          42,
          0,
        );
        final volumeMaxParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          44,
          0,
        );
        final volumeStepParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          46,
          0,
        );
        final askDifferenceParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          48,
          0,
        );
        final bidDifferenceParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          50,
          0,
        );
        final stopLevelParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          52,
          0,
        );
        final isFavParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          54,
          false,
        );
        final indexParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          56,
          0,
        );
        final object = SymbolModel(
          id: idParam,
          marginCurrency: marginCurrencyParam,
          profitCurrency: profitCurrencyParam,
          description: descriptionParam,
          sector: sectorParam,
          name: nameParam,
          leverage: leverageParam,
          ask: askParam,
          bid: bidParam,
          askColorHex: askColorHexParam,
          bidColorHex: bidColorHexParam,
          timestamp: timestampParam,
          groupSymbol: groupSymbolParam,
          contractSize: contractSizeParam,
          tickSize: tickSizeParam,
          profitRatio: profitRatioParam,
          marginRatio: marginRatioParam,
          swapLong: swapLongParam,
          swapShort: swapShortParam,
          commissionIn: commissionInParam,
          commissionOut: commissionOutParam,
          volumeMin: volumeMinParam,
          volumeMax: volumeMaxParam,
          volumeStep: volumeStepParam,
          askDifference: askDifferenceParam,
          bidDifference: bidDifferenceParam,
          stopLevel: stopLevelParam,
          isFav: isFavParam,
          index: indexParam,
        );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [AccountFoundsModel] entity fields to define ObjectBox queries.
class AccountFoundsModel_ {
  /// See [AccountFoundsModel.id].
  static final id = obx.QueryIntegerProperty<AccountFoundsModel>(
    _entities[0].properties[0],
  );

  /// See [AccountFoundsModel.type].
  static final type = obx.QueryStringProperty<AccountFoundsModel>(
    _entities[0].properties[1],
  );

  /// See [AccountFoundsModel.amount].
  static final amount = obx.QueryDoubleProperty<AccountFoundsModel>(
    _entities[0].properties[2],
  );

  /// See [AccountFoundsModel.comment].
  static final comment = obx.QueryStringProperty<AccountFoundsModel>(
    _entities[0].properties[3],
  );

  /// See [AccountFoundsModel.source].
  static final source = obx.QueryStringProperty<AccountFoundsModel>(
    _entities[0].properties[4],
  );

  /// See [AccountFoundsModel.date].
  static final date = obx.QueryStringProperty<AccountFoundsModel>(
    _entities[0].properties[5],
  );

  /// See [AccountFoundsModel.commission].
  static final commission = obx.QueryDoubleProperty<AccountFoundsModel>(
    _entities[0].properties[6],
  );

  /// See [AccountFoundsModel.isA].
  static final isA = obx.QueryStringProperty<AccountFoundsModel>(
    _entities[0].properties[7],
  );

  /// See [AccountFoundsModel.swap].
  static final swap = obx.QueryDoubleProperty<AccountFoundsModel>(
    _entities[0].properties[8],
  );
}

/// [AppLogModel] entity fields to define ObjectBox queries.
class AppLogModel_ {
  /// See [AppLogModel.id].
  static final id = obx.QueryIntegerProperty<AppLogModel>(
    _entities[1].properties[0],
  );

  /// See [AppLogModel.accountNumber].
  static final accountNumber = obx.QueryIntegerProperty<AppLogModel>(
    _entities[1].properties[1],
  );

  /// See [AppLogModel.event].
  static final event = obx.QueryStringProperty<AppLogModel>(
    _entities[1].properties[2],
  );

  /// See [AppLogModel.createdAt].
  static final createdAt = obx.QueryDateProperty<AppLogModel>(
    _entities[1].properties[3],
  );
}

/// [ConnectedAccountInfoModel] entity fields to define ObjectBox queries.
class ConnectedAccountInfoModel_ {
  /// See [ConnectedAccountInfoModel.id].
  static final id = obx.QueryIntegerProperty<ConnectedAccountInfoModel>(
    _entities[2].properties[0],
  );

  /// See [ConnectedAccountInfoModel.group].
  static final group = obx.QueryStringProperty<ConnectedAccountInfoModel>(
    _entities[2].properties[1],
  );

  /// See [ConnectedAccountInfoModel.fullName].
  static final fullName = obx.QueryStringProperty<ConnectedAccountInfoModel>(
    _entities[2].properties[2],
  );

  /// See [ConnectedAccountInfoModel.leverage].
  static final leverage = obx.QueryIntegerProperty<ConnectedAccountInfoModel>(
    _entities[2].properties[3],
  );

  /// See [ConnectedAccountInfoModel.balance].
  static final balance = obx.QueryDoubleProperty<ConnectedAccountInfoModel>(
    _entities[2].properties[4],
  );

  /// See [ConnectedAccountInfoModel.credit].
  static final credit = obx.QueryDoubleProperty<ConnectedAccountInfoModel>(
    _entities[2].properties[5],
  );

  /// See [ConnectedAccountInfoModel.equity].
  static final equity = obx.QueryDoubleProperty<ConnectedAccountInfoModel>(
    _entities[2].properties[6],
  );

  /// See [ConnectedAccountInfoModel.floating].
  static final floating = obx.QueryDoubleProperty<ConnectedAccountInfoModel>(
    _entities[2].properties[7],
  );

  /// See [ConnectedAccountInfoModel.margin].
  static final margin = obx.QueryDoubleProperty<ConnectedAccountInfoModel>(
    _entities[2].properties[8],
  );

  /// See [ConnectedAccountInfoModel.marginFree].
  static final marginFree = obx.QueryDoubleProperty<ConnectedAccountInfoModel>(
    _entities[2].properties[9],
  );

  /// See [ConnectedAccountInfoModel.marginLevel].
  static final marginLevel = obx.QueryDoubleProperty<ConnectedAccountInfoModel>(
    _entities[2].properties[10],
  );

  /// See [ConnectedAccountInfoModel.isSwapFree].
  static final isSwapFree = obx.QueryBooleanProperty<ConnectedAccountInfoModel>(
    _entities[2].properties[11],
  );

  /// See [ConnectedAccountInfoModel.limitPositions].
  static final limitPositions =
      obx.QueryIntegerProperty<ConnectedAccountInfoModel>(
        _entities[2].properties[12],
      );

  /// See [ConnectedAccountInfoModel.limitPending].
  static final limitPending =
      obx.QueryIntegerProperty<ConnectedAccountInfoModel>(
        _entities[2].properties[13],
      );

  /// See [ConnectedAccountInfoModel.rights].
  static final rights = obx.QueryIntegerProperty<ConnectedAccountInfoModel>(
    _entities[2].properties[14],
  );

  /// See [ConnectedAccountInfoModel.isDefault].
  static final isDefault = obx.QueryBooleanProperty<ConnectedAccountInfoModel>(
    _entities[2].properties[15],
  );

  /// See [ConnectedAccountInfoModel.marginCallLevel].
  static final marginCallLevel =
      obx.QueryDoubleProperty<ConnectedAccountInfoModel>(
        _entities[2].properties[16],
      );

  /// See [ConnectedAccountInfoModel.connectionMode].
  static final connectionMode =
      obx.QueryStringProperty<ConnectedAccountInfoModel>(
        _entities[2].properties[17],
      );
}

/// [HistoryActionModel] entity fields to define ObjectBox queries.
class HistoryActionModel_ {
  /// See [HistoryActionModel.id].
  static final id = obx.QueryIntegerProperty<HistoryActionModel>(
    _entities[3].properties[0],
  );

  /// See [HistoryActionModel.account].
  static final account = obx.QueryIntegerProperty<HistoryActionModel>(
    _entities[3].properties[1],
  );

  /// See [HistoryActionModel.symbol].
  static final symbol = obx.QueryStringProperty<HistoryActionModel>(
    _entities[3].properties[2],
  );

  /// See [HistoryActionModel.source].
  static final source = obx.QueryStringProperty<HistoryActionModel>(
    _entities[3].properties[3],
  );

  /// See [HistoryActionModel.direction].
  static final direction = obx.QueryStringProperty<HistoryActionModel>(
    _entities[3].properties[4],
  );

  /// See [HistoryActionModel.type].
  static final type = obx.QueryStringProperty<HistoryActionModel>(
    _entities[3].properties[5],
  );

  /// See [HistoryActionModel.volume].
  static final volume = obx.QueryDoubleProperty<HistoryActionModel>(
    _entities[3].properties[6],
  );

  /// See [HistoryActionModel.commission].
  static final commission = obx.QueryDoubleProperty<HistoryActionModel>(
    _entities[3].properties[7],
  );

  /// See [HistoryActionModel.price].
  static final price = obx.QueryDoubleProperty<HistoryActionModel>(
    _entities[3].properties[8],
  );

  /// See [HistoryActionModel.profit].
  static final profit = obx.QueryDoubleProperty<HistoryActionModel>(
    _entities[3].properties[9],
  );

  /// See [HistoryActionModel.createdAt].
  static final createdAt = obx.QueryStringProperty<HistoryActionModel>(
    _entities[3].properties[10],
  );

  /// See [HistoryActionModel.tradeId].
  static final tradeId = obx.QueryIntegerProperty<HistoryActionModel>(
    _entities[3].properties[11],
  );
}

/// [HistoryPendingModel] entity fields to define ObjectBox queries.
class HistoryPendingModel_ {
  /// See [HistoryPendingModel.id].
  static final id = obx.QueryIntegerProperty<HistoryPendingModel>(
    _entities[4].properties[0],
  );

  /// See [HistoryPendingModel.symbol].
  static final symbol = obx.QueryStringProperty<HistoryPendingModel>(
    _entities[4].properties[1],
  );

  /// See [HistoryPendingModel.direction].
  static final direction = obx.QueryStringProperty<HistoryPendingModel>(
    _entities[4].properties[2],
  );

  /// See [HistoryPendingModel.expirationDate].
  static final expirationDate = obx.QueryStringProperty<HistoryPendingModel>(
    _entities[4].properties[3],
  );

  /// See [HistoryPendingModel.createdAt].
  static final createdAt = obx.QueryStringProperty<HistoryPendingModel>(
    _entities[4].properties[4],
  );

  /// See [HistoryPendingModel.volume].
  static final volume = obx.QueryDoubleProperty<HistoryPendingModel>(
    _entities[4].properties[5],
  );

  /// See [HistoryPendingModel.openPrice].
  static final openPrice = obx.QueryDoubleProperty<HistoryPendingModel>(
    _entities[4].properties[6],
  );

  /// See [HistoryPendingModel.tp].
  static final tp = obx.QueryDoubleProperty<HistoryPendingModel>(
    _entities[4].properties[7],
  );

  /// See [HistoryPendingModel.sl].
  static final sl = obx.QueryDoubleProperty<HistoryPendingModel>(
    _entities[4].properties[8],
  );

  /// See [HistoryPendingModel.type].
  static final type = obx.QueryIntegerProperty<HistoryPendingModel>(
    _entities[4].properties[9],
  );

  /// See [HistoryPendingModel.comment].
  static final comment = obx.QueryStringProperty<HistoryPendingModel>(
    _entities[4].properties[10],
  );

  /// See [HistoryPendingModel.openTime].
  static final openTime = obx.QueryStringProperty<HistoryPendingModel>(
    _entities[4].properties[11],
  );

  /// See [HistoryPendingModel.closedAt].
  static final closedAt = obx.QueryStringProperty<HistoryPendingModel>(
    _entities[4].properties[12],
  );

  /// See [HistoryPendingModel.reason].
  static final reason = obx.QueryStringProperty<HistoryPendingModel>(
    _entities[4].properties[13],
  );
}

/// [HistoryPositionModel] entity fields to define ObjectBox queries.
class HistoryPositionModel_ {
  /// See [HistoryPositionModel.id].
  static final id = obx.QueryIntegerProperty<HistoryPositionModel>(
    _entities[5].properties[0],
  );

  /// See [HistoryPositionModel.symbol].
  static final symbol = obx.QueryStringProperty<HistoryPositionModel>(
    _entities[5].properties[1],
  );

  /// See [HistoryPositionModel.direction].
  static final direction = obx.QueryStringProperty<HistoryPositionModel>(
    _entities[5].properties[2],
  );

  /// See [HistoryPositionModel.volumeInit].
  static final volumeInit = obx.QueryDoubleProperty<HistoryPositionModel>(
    _entities[5].properties[3],
  );

  /// See [HistoryPositionModel.volumeCurrent].
  static final volumeCurrent = obx.QueryDoubleProperty<HistoryPositionModel>(
    _entities[5].properties[4],
  );

  /// See [HistoryPositionModel.openPrice].
  static final openPrice = obx.QueryDoubleProperty<HistoryPositionModel>(
    _entities[5].properties[5],
  );

  /// See [HistoryPositionModel.tp].
  static final tp = obx.QueryDoubleProperty<HistoryPositionModel>(
    _entities[5].properties[6],
  );

  /// See [HistoryPositionModel.sl].
  static final sl = obx.QueryDoubleProperty<HistoryPositionModel>(
    _entities[5].properties[7],
  );

  /// See [HistoryPositionModel.floating].
  static final floating = obx.QueryDoubleProperty<HistoryPositionModel>(
    _entities[5].properties[8],
  );

  /// See [HistoryPositionModel.margin].
  static final margin = obx.QueryDoubleProperty<HistoryPositionModel>(
    _entities[5].properties[9],
  );

  /// See [HistoryPositionModel.commission].
  static final commission = obx.QueryDoubleProperty<HistoryPositionModel>(
    _entities[5].properties[10],
  );

  /// See [HistoryPositionModel.swap].
  static final swap = obx.QueryDoubleProperty<HistoryPositionModel>(
    _entities[5].properties[11],
  );

  /// See [HistoryPositionModel.comment].
  static final comment = obx.QueryStringProperty<HistoryPositionModel>(
    _entities[5].properties[12],
  );

  /// See [HistoryPositionModel.openTime].
  static final openTime = obx.QueryStringProperty<HistoryPositionModel>(
    _entities[5].properties[13],
  );

  /// See [HistoryPositionModel.closePrice].
  static final closePrice = obx.QueryDoubleProperty<HistoryPositionModel>(
    _entities[5].properties[14],
  );

  /// See [HistoryPositionModel.closeTime].
  static final closeTime = obx.QueryStringProperty<HistoryPositionModel>(
    _entities[5].properties[15],
  );
}

/// [OrderModel] entity fields to define ObjectBox queries.
class OrderModel_ {
  /// See [OrderModel.id].
  static final id = obx.QueryIntegerProperty<OrderModel>(
    _entities[6].properties[0],
  );

  /// See [OrderModel.symbol].
  static final symbol = obx.QueryStringProperty<OrderModel>(
    _entities[6].properties[1],
  );

  /// See [OrderModel.direction].
  static final direction = obx.QueryStringProperty<OrderModel>(
    _entities[6].properties[2],
  );

  /// See [OrderModel.expirationDate].
  static final expirationDate = obx.QueryStringProperty<OrderModel>(
    _entities[6].properties[3],
  );

  /// See [OrderModel.createdAt].
  static final createdAt = obx.QueryStringProperty<OrderModel>(
    _entities[6].properties[4],
  );

  /// See [OrderModel.volume].
  static final volume = obx.QueryDoubleProperty<OrderModel>(
    _entities[6].properties[5],
  );

  /// See [OrderModel.openPrice].
  static final openPrice = obx.QueryDoubleProperty<OrderModel>(
    _entities[6].properties[6],
  );

  /// See [OrderModel.tp].
  static final tp = obx.QueryDoubleProperty<OrderModel>(
    _entities[6].properties[7],
  );

  /// See [OrderModel.sl].
  static final sl = obx.QueryDoubleProperty<OrderModel>(
    _entities[6].properties[8],
  );

  /// See [OrderModel.comment].
  static final comment = obx.QueryStringProperty<OrderModel>(
    _entities[6].properties[9],
  );

  /// See [OrderModel.openTime].
  static final openTime = obx.QueryStringProperty<OrderModel>(
    _entities[6].properties[10],
  );
}

/// [PositionModel] entity fields to define ObjectBox queries.
class PositionModel_ {
  /// See [PositionModel.id].
  static final id = obx.QueryIntegerProperty<PositionModel>(
    _entities[7].properties[0],
  );

  /// See [PositionModel.groupSymbol].
  static final groupSymbol = obx.QueryStringProperty<PositionModel>(
    _entities[7].properties[1],
  );

  /// See [PositionModel.direction].
  static final direction = obx.QueryStringProperty<PositionModel>(
    _entities[7].properties[2],
  );

  /// See [PositionModel.volumeInit].
  static final volumeInit = obx.QueryDoubleProperty<PositionModel>(
    _entities[7].properties[3],
  );

  /// See [PositionModel.volumeCurrent].
  static final volumeCurrent = obx.QueryDoubleProperty<PositionModel>(
    _entities[7].properties[4],
  );

  /// See [PositionModel.openPrice].
  static final openPrice = obx.QueryDoubleProperty<PositionModel>(
    _entities[7].properties[5],
  );

  /// See [PositionModel.tp].
  static final tp = obx.QueryDoubleProperty<PositionModel>(
    _entities[7].properties[6],
  );

  /// See [PositionModel.sl].
  static final sl = obx.QueryDoubleProperty<PositionModel>(
    _entities[7].properties[7],
  );

  /// See [PositionModel.floating].
  static final floating = obx.QueryDoubleProperty<PositionModel>(
    _entities[7].properties[8],
  );

  /// See [PositionModel.margin].
  static final margin = obx.QueryDoubleProperty<PositionModel>(
    _entities[7].properties[9],
  );

  /// See [PositionModel.commission].
  static final commission = obx.QueryDoubleProperty<PositionModel>(
    _entities[7].properties[10],
  );

  /// See [PositionModel.swap].
  static final swap = obx.QueryDoubleProperty<PositionModel>(
    _entities[7].properties[11],
  );

  /// See [PositionModel.comment].
  static final comment = obx.QueryStringProperty<PositionModel>(
    _entities[7].properties[12],
  );

  /// See [PositionModel.openTime].
  static final openTime = obx.QueryStringProperty<PositionModel>(
    _entities[7].properties[13],
  );
}

/// [SymbolModel] entity fields to define ObjectBox queries.
class SymbolModel_ {
  /// See [SymbolModel.id].
  static final id = obx.QueryIntegerProperty<SymbolModel>(
    _entities[8].properties[0],
  );

  /// See [SymbolModel.sector].
  static final sector = obx.QueryStringProperty<SymbolModel>(
    _entities[8].properties[1],
  );

  /// See [SymbolModel.name].
  static final name = obx.QueryStringProperty<SymbolModel>(
    _entities[8].properties[2],
  );

  /// See [SymbolModel.leverage].
  static final leverage = obx.QueryIntegerProperty<SymbolModel>(
    _entities[8].properties[3],
  );

  /// See [SymbolModel.ask].
  static final ask = obx.QueryDoubleProperty<SymbolModel>(
    _entities[8].properties[4],
  );

  /// See [SymbolModel.bid].
  static final bid = obx.QueryDoubleProperty<SymbolModel>(
    _entities[8].properties[5],
  );

  /// See [SymbolModel.marginCurrency].
  static final marginCurrency = obx.QueryStringProperty<SymbolModel>(
    _entities[8].properties[6],
  );

  /// See [SymbolModel.description].
  static final description = obx.QueryStringProperty<SymbolModel>(
    _entities[8].properties[7],
  );

  /// See [SymbolModel.profitCurrency].
  static final profitCurrency = obx.QueryStringProperty<SymbolModel>(
    _entities[8].properties[8],
  );

  /// See [SymbolModel.timestamp].
  static final timestamp = obx.QueryIntegerProperty<SymbolModel>(
    _entities[8].properties[9],
  );

  /// See [SymbolModel.groupSymbol].
  static final groupSymbol = obx.QueryDoubleProperty<SymbolModel>(
    _entities[8].properties[10],
  );

  /// See [SymbolModel.contractSize].
  static final contractSize = obx.QueryDoubleProperty<SymbolModel>(
    _entities[8].properties[11],
  );

  /// See [SymbolModel.tickSize].
  static final tickSize = obx.QueryDoubleProperty<SymbolModel>(
    _entities[8].properties[12],
  );

  /// See [SymbolModel.profitRatio].
  static final profitRatio = obx.QueryDoubleProperty<SymbolModel>(
    _entities[8].properties[13],
  );

  /// See [SymbolModel.marginRatio].
  static final marginRatio = obx.QueryDoubleProperty<SymbolModel>(
    _entities[8].properties[14],
  );

  /// See [SymbolModel.swapLong].
  static final swapLong = obx.QueryDoubleProperty<SymbolModel>(
    _entities[8].properties[15],
  );

  /// See [SymbolModel.swapShort].
  static final swapShort = obx.QueryDoubleProperty<SymbolModel>(
    _entities[8].properties[16],
  );

  /// See [SymbolModel.commissionIn].
  static final commissionIn = obx.QueryDoubleProperty<SymbolModel>(
    _entities[8].properties[17],
  );

  /// See [SymbolModel.commissionOut].
  static final commissionOut = obx.QueryDoubleProperty<SymbolModel>(
    _entities[8].properties[18],
  );

  /// See [SymbolModel.volumeMin].
  static final volumeMin = obx.QueryDoubleProperty<SymbolModel>(
    _entities[8].properties[19],
  );

  /// See [SymbolModel.volumeMax].
  static final volumeMax = obx.QueryDoubleProperty<SymbolModel>(
    _entities[8].properties[20],
  );

  /// See [SymbolModel.volumeStep].
  static final volumeStep = obx.QueryDoubleProperty<SymbolModel>(
    _entities[8].properties[21],
  );

  /// See [SymbolModel.askDifference].
  static final askDifference = obx.QueryDoubleProperty<SymbolModel>(
    _entities[8].properties[22],
  );

  /// See [SymbolModel.bidDifference].
  static final bidDifference = obx.QueryDoubleProperty<SymbolModel>(
    _entities[8].properties[23],
  );

  /// See [SymbolModel.stopLevel].
  static final stopLevel = obx.QueryIntegerProperty<SymbolModel>(
    _entities[8].properties[24],
  );

  /// See [SymbolModel.isFav].
  static final isFav = obx.QueryBooleanProperty<SymbolModel>(
    _entities[8].properties[25],
  );

  /// See [SymbolModel.index].
  static final index = obx.QueryIntegerProperty<SymbolModel>(
    _entities[8].properties[26],
  );

  /// See [SymbolModel.askColorHex].
  static final askColorHex = obx.QueryStringProperty<SymbolModel>(
    _entities[8].properties[27],
  );

  /// See [SymbolModel.bidColorHex].
  static final bidColorHex = obx.QueryStringProperty<SymbolModel>(
    _entities[8].properties[28],
  );
}
